### ISSUE TITLE
Issue during normalization code used in email dataset

### ISSUE THREAD

**Issue by imwaqasakrax** [alok-ai-lab/DeepInsight#10]
Hope everything fine . I am researcher student . I seen DeepInsight and have interest to used but when i used command normalization both  have  some error more my dataset email spam filter have 2 column but normalization code used only 1 when i give 2 column give error of TypeError: bad operand type for abs(): 'str' , second ValueError: Found array with 1 sample(s) (shape=(1, 4136)) while a minimum of 2 is required.  and when give 1 run code more at the point of transformation test and train give image tannsformation error coods  please specify error fix.

**Comment by alok-ai-lab** [comment]
Are you using DeepInsight in Matlab or in Python? Do you have any NaN elements in your dataset?

**Comment by imwaqasakrax** [comment]
Using DeepInsight in Python , My dataset have not NaN values but have great numbers of string like proper emails

**Comment by alok-ai-lab** [comment]
You have to convert string into numerical values before you can apply DeepInsight. 
Perhaps you may consider using some feature extractors for conversion of string data to numerical representation.

**Comment by imwaqasakrax** [comment]
Ok sir thank u so much
