### ISSUE TITLE
Where To Find Documentation Of Functions?

### ISSUE THREAD

**Issue by spot92** [alok-ai-lab/DeepInsight#11]
Curious specifically about the difference between fit_transform and transform.

**Comment by kaboroevich** [comment]
The documentation is in docstring format following the [Google style convention](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings). You can access these as follows;

```
import pyDeepInsight
help(pyDeepInsight.ImageTransformer().fit_transform)
```

The methods `fit()`, `transform()`, and `fit_transform()` follow the [scikit-learn](https://scikit-learn.org/stable/) naming conventions.  `fit()` calculates the parameters of the transformation using the input data, `transform()` applies the transformation to the input data, and `fit_transform()` does both fit and transform in a single step. Generally, you use `fit_transform()` on the training data and `transform()` on the test data. 

You can read a more in-depth explanation on [Towards Data Science: What and why behind fit_transform() and transform() in scikit-learn!](https://towardsdatascience.com/what-and-why-behind-fit-transform-vs-transform-in-scikit-learn-78f915cf96fe)
