### ISSUE TITLE
[Data augmentation]

### ISSUE THREAD

**Issue by Hchang77** [alok-ai-lab/DeepInsight#13]
Hello

I try to apply the DeepInsight to RNA seq data of cancer patients and, search for the method for improving the accuracy of CNN model.

Because the shape of plots for the image matrices from DeepInsight looks same, but only color density of pixels are different, I wonder the data augmentation is proper for improvement of the accuracy

Could you recommend how to improve the accuracy of CNN model with images from DeepInsight?

Regards,

**Comment by kaboroevich** [comment]
In the original manuscript for DeepInsight, [Table 2](https://www.nature.com/articles/s41598-019-47765-6/tables/2) shows the accuracy for the DeepInsight approach versus other common methods for the TCGA classification of cancer types. The improvement of accuracy will depend on the specific problem. I suggest doing your own comparison to see if DeepInsight improves accuracy in your study.

With regards to data augmentation. You would not be able to apply data augmentation to the images DeepInsight produces as the genes-pixel mapping should remain fixed. Data augmentation prior to applying DeepInsight, for example, to correct for class imbalance, would be acceptable and could improve performance in certain cases.
