### ISSUE TITLE
can we find how many genes are placed in a single pixel location?

### ISSUE THREAD

**Issue by phd-21** [alok-ai-lab/DeepInsight#14]
I have the data in the pandas data frame with the following shape.

(200, 24842)
Now, when I apply data to the transform function, I get image data of the shape.
(200,120X120)
Is any method you created that can guide me to find out how many genes are placed in a single pixel location and which are those?

**Comment by kaboroevich** [comment]
Yes, this is available through the `.feature_density_matrix()` method covered in the README.md.

Please see the code after the line "The feature density matrix can be extracted from the trained transformer in order to view overall feature overlap".

**Comment by kaboroevich** [comment]
For determining which pixel a given gene is at, you can use the `.coords()` method to return the pixel location of all features/genes.

**Comment by kaboroevich** [comment]
Closed due to inactivity - if your question is not answered, please feel free to reopen.
