### ISSUE TITLE
Installation error on Ubuntu 18.04 LTS for py 

### ISSUE THREAD

**Issue by omeshF** [alok-ai-lab/DeepInsight#3]
I'm trying to install this using python to a Ubuntu 18.04 machine. As I run the command for installation, I get the following error. Please see the text below. 

  $ python -m pip -q install git+git://github.com/alok-ai-lab/DeepInsight.git#egg=DeepInsight

  Could not find a version that satisfies the requirement scikit-learn>=0.22 (from DeepInsight) (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18rc2, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2)
No matching distribution found for scikit-learn>=0.22 (from DeepInsight)

The error prompts for the scikit-learn package.   I have already installed this on my system. Please see below. 

$ python3 -m pip show scikit-learn
Name: scikit-learn
Version: 0.24.1
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: None
Author-email: None
License: new BSD
Location: /home/s7com1030/.local/lib/python3.6/site-packages
Requires: threadpoolctl, joblib, scipy, numpy

If you could kindly assist me in rectifying this error and installing this in my system, I would sincerely appreciate it. Awaiting to hear from you at your earliest. :) 

PS: I have cloned the dir into my home and ran the first installation command.

**Comment by kaboroevich** [comment]
Change the `python -m pip -q install git+git://github.com/alok-ai-lab/DeepInsight.git#egg=DeepInsight` to `python3 -m pip -q install git+git://github.com/alok-ai-lab/DeepInsight.git#egg=DeepInsight`.

I will update the README accordingly.
