### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by scchess** [alok-ai-lab/DeepInsight#5]
Hi. I followed the tutorial but supplied my own RNA gene matrix. It looked a standard gene expression inputs to me. However, I'm getting:

    ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Any idea?

**Comment by kaboroevich** [comment]
Can you post the full error report? I'm guessing you have nan values in your input, but more information about the error is needed.

**Comment by scchess** [comment]
Sorry. I've resolved it. The Python image transformer expected numpy array, but `read_csv()` gave it a Pandas Dataframe. After I converted the dataframe to a proper numpy array, it all went good.
