### ISSUE TITLE
Using the framework on EEG data (Python 3, Anaconda)

### ISSUE THREAD

**Issue by meyiduleme** [alok-ai-lab/DeepInsight#6]
Hello, I'd like to adapt the DeepInsight framework to my EEG data. On your README you qualified it of "experimental". How should I do, please? Or what are the experimental / non-experimental sections of the code.

Thanks in advance

**Comment by kaboroevich** [comment]
By experimental, I mean the results are not guaranteed to match the original MatLab results, their may be unknown/unresolved bugs in the current code, and the interface may change in the future in such a way it is not backwards compatible.

If you are comfortable with that, feel free to use the framework for anything you see fit.
