### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by meyiduleme** [alok-ai-lab/DeepInsight#7]
Hello! That's me again... I can't install the pyDeepInsight... Is that the right path? Thanks!

**Comment by kaboroevich** [comment]
Can you please post what command you ran, and what the entire error report was.

**Comment by meyiduleme** [comment]
Windows 64 cmd:
pip install git+git://github.com/alok-ai-lab/DeepInsight.git#egg=DeepInsight


Error:
Command "git clone -q git://github.com/alok-ai-lab/DeepInsight.git#egg=DeepInsight C://Users/mduleme/AppData/Local/Temp/pip-req-build-fgc844i8' failed with error code 128 in None

Thank you!

**Comment by ttalaeik** [comment]
have similar problem

**Comment by kaboroevich** [comment]
I'm not very familiar with python on windows. It appears to be an issue with downloading from git. Is git installed on your system? Also, is the `pip` linked to python2 or python3?

**Comment by kaboroevich** [comment]
Closing this issue due to a lack of response. Can reopen if it's determined to be a pyDeepInsight issue and not a system issue.
